language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - "node_modules"
before_install:
  - npm update
install:
  - npm install
env:
  global:
    - NODE_ENV=test
script:
  - npm test
after_success:
  - npm run coverage